// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC204dRa3DnGuRS-0BmqCTWusPTOFwNYxc',
    appId: '1:105164204168:web:23acae2720f849c021173d',
    messagingSenderId: '105164204168',
    projectId: 'sasta-bazar-ce121',
    authDomain: 'sasta-bazar-ce121.firebaseapp.com',
    storageBucket: 'sasta-bazar-ce121.appspot.com',
    measurementId: 'G-68MH12KB6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiBo4piS08Khi_dTsms5so-oRa0bHjtrw',
    appId: '1:105164204168:android:5faa5676c4a8057d21173d',
    messagingSenderId: '105164204168',
    projectId: 'sasta-bazar-ce121',
    storageBucket: 'sasta-bazar-ce121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgfJoneroDzMdpZVX6i8NTKie6DQccCJ0',
    appId: '1:105164204168:ios:e5a97cc249f0b63321173d',
    messagingSenderId: '105164204168',
    projectId: 'sasta-bazar-ce121',
    storageBucket: 'sasta-bazar-ce121.appspot.com',
    iosBundleId: 'com.example.sastaBazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgfJoneroDzMdpZVX6i8NTKie6DQccCJ0',
    appId: '1:105164204168:ios:e5a97cc249f0b63321173d',
    messagingSenderId: '105164204168',
    projectId: 'sasta-bazar-ce121',
    storageBucket: 'sasta-bazar-ce121.appspot.com',
    iosBundleId: 'com.example.sastaBazar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC204dRa3DnGuRS-0BmqCTWusPTOFwNYxc',
    appId: '1:105164204168:web:1594f690bce50d1b21173d',
    messagingSenderId: '105164204168',
    projectId: 'sasta-bazar-ce121',
    authDomain: 'sasta-bazar-ce121.firebaseapp.com',
    storageBucket: 'sasta-bazar-ce121.appspot.com',
    measurementId: 'G-SF1N0E5JJ1',
  );
}
